services:
  ethrex-zisk:
    image: ghcr.io/eth-act/ere/ere-server-zisk:0.9.1-cuda
    command:
      - "--port"
      - "3000"
      - "--elf-url"
      - "https://github.com/eth-act/ere-guests/releases/download/v0.10.0/stateless-validator-ethrex-zisk.elf"
      - "gpu"
    shm_size: 32G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - zkboost
    environment:
      - RUST_LOG=info,asm_runner=warn,executor=warn,mem_planner_cpp=warn,proofman=warn,rom_setup=warn,sm_rom=warn,zisk=warn
      - ERE_ZISK_SETUP_ON_INIT=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      start_period: 300s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3']
              capabilities: [gpu]

  reth-zisk:
    extends: ethrex-zisk
    command:
      - "--port"
      - "3000"
      - "--elf-url"
      - "https://github.com/eth-act/ere-guests/releases/download/v0.10.0/stateless-validator-reth-zisk.elf"
      - "gpu"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['4', '5', '6', '7']
              capabilities: [gpu]

  zkboost:
    image: zkboost:local
    build:
      context: ../../..
      dockerfile: ./docker/Dockerfile
    command: ["--config", "/app/config.toml"]
    ports:
      - "3000:3000"
    depends_on:
      ethrex-zisk:
        condition: service_healthy
      reth-zisk:
        condition: service_healthy
    volumes:
      - ./zkboost/config.toml:/app/config.toml:ro
    networks:
      - zkboost
      - kurtosis
    environment:
      - RUST_LOG=info,zkboost=debug
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      start_period: 1s
      start_interval: 1s

networks:
  zkboost:
    name: zkboost-local-testnet
  kurtosis:
    external: true
    name: kt-local-testnet
