participants:
  - cl_type: lighthouse
    cl_image: ethpandaops/lighthouse:eth-act-optional-proofs
    el_type: reth
    el_image: ghcr.io/paradigmxyz/reth
    supernode: true
    cl_extra_params:
      - --target-peers=3
      - --proof-engine-endpoint=http://zkboost:3000
      - --proof-types=2,6
    vc_extra_params:
      - --proof-engine-endpoint=http://zkboost:3000
      - --proof-types=2,6
    count: 2
  - cl_type: lighthouse
    cl_image: ethpandaops/lighthouse:eth-act-optional-proofs
    el_type: None
    supernode: false
    cl_extra_params:
      - --target-peers=3
      - --proof-engine-endpoint=http://zkboost:3000
      - --proof-types=2,6
    count: 1

network_params:
  seconds_per_slot: 12

additional_services:
  - spamoor

spamoor_params:
  spammers:
    - scenario: "erctx"
      config:
        throughput: 1

