[package]
name = "mock-zkattestor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
axum.workspace = true
clap = { workspace = true, features = ["derive"] }
futures.workspace = true
jsonwebtoken.workspace = true
reqwest = { workspace = true, features = ["json"] }
reqwest-eventsource.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url.workspace = true

# alloy
alloy-rpc-types-engine = { workspace = true, features = ["jwt"] }

# ere
ere-verifier.workspace = true

# lighthouse
lighthouse_bls.workspace = true
ethereum_serde_utils.workspace = true
lighthouse_types.workspace = true

# local
zkboost-types.workspace = true
