port = 3000
el_endpoint = "http://host.docker.internal:32003"

[[zkvm]]
kind = "external"
endpoint = "http://ethrex-zisk:3000"
proof_type = "ethrex-zisk"

[[zkvm]]
kind = "external"
endpoint = "http://reth-zisk:3000"
proof_type = "reth-zisk"
