participants:
  - el_type: reth
    cl_type: lighthouse
    count: 3
network_params:
  seconds_per_slot: 12
global_log_level: debug
snooper_enabled: false
additional_services:
  - dora
  - prometheus_grafana
port_publisher:
  el:
    enabled: true
    public_port_start: 32000
  cl:
    enabled: true
    public_port_start: 33000
