name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        toolchain: [1.93.1]
    steps:
      - uses: actions/checkout@v4

      # Needed for crate `sp1-prover-types` (dep of `ere-verifier`)
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: rustfmt
        run: |
          rustup toolchain install nightly --profile minimal --component rustfmt
          cargo +nightly fmt --all --check

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: cargo test
        run: cargo test --release --workspace --all-features --no-fail-fast
